%% Analyze packet-specific slow phase wander from repetition CIR
% Uses exactly the estimator consumed by run_cancel_all_uwb_packets.m.

clearvars;
close all;
clc;

project_dir = fileparts(mfilename('fullpath'));
result_name = 'qm35_new_3';
scan_file = fullfile(project_dir, 'decoded_results', result_name, ...
    'all_frames_cir.mat');
output_dir = fullfile(project_dir, 'decoded_results', ...
    'cir_slow_phase_analysis', result_name);
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

estimator_options = struct( ...
    'tap_half_width', 2, ...
    'smoothing_lambda', 0.10, ...
    'minimum_subspace_coherence', 0.85, ...
    'minimum_correction_rms_deg', 0.20, ...
    'minimum_explained_fraction', 0.10, ...
    'maximum_abs_correction_deg', 15.0);

loaded = load(scan_file, 'results');
results = loaded.results;
frames = results.frames;
preamble_repetitions = results.params.preamble_repetitions;
packet_count = numel(frames);

prototype = struct( ...
    'packet_index', 0, ...
    'fcs_pass', false, ...
    'applied', false, ...
    'first_repetition', 0, ...
    'last_repetition', 0, ...
    'subspace_coherence', NaN, ...
    'raw_nonlinear_rms_deg', NaN, ...
    'correction_rms_deg', NaN, ...
    'noise_rms_deg', NaN, ...
    'maximum_abs_correction_deg', NaN, ...
    'explained_fraction', NaN);
packet_report = repmat(prototype, packet_count, 1);
phase_tracks = NaN(packet_count, preamble_repetitions);

for k = 1:packet_count
    frame = frames(k);
    [phase, diagnostics] = estimate_uwb_cir_slow_phase( ...
        frame.cir, preamble_repetitions, estimator_options);
    packet_report(k).packet_index = frame.index;
    packet_report(k).fcs_pass = logical(frame.fcs_pass);
    packet_report(k).applied = diagnostics.applied;
    packet_report(k).first_repetition = diagnostics.first_repetition;
    packet_report(k).last_repetition = diagnostics.last_repetition;
    packet_report(k).subspace_coherence = diagnostics.subspace_coherence;
    packet_report(k).raw_nonlinear_rms_deg = ...
        diagnostics.raw_nonlinear_rms_deg;
    packet_report(k).correction_rms_deg = diagnostics.correction_rms_deg;
    packet_report(k).noise_rms_deg = diagnostics.noise_rms_deg;
    packet_report(k).maximum_abs_correction_deg = ...
        diagnostics.maximum_abs_correction_deg;
    packet_report(k).explained_fraction = diagnostics.explained_fraction;
    if diagnostics.applied
        phase_tracks(k, :) = phase;
    end
end

packet_table = struct2table(packet_report);
writetable(packet_table, fullfile(output_dir, ...
    'cir_slow_phase_packet_summary.csv'));
save(fullfile(output_dir, 'cir_slow_phase_analysis.mat'), ...
    'packet_report', 'packet_table', 'phase_tracks', ...
    'estimator_options', 'scan_file', '-v7.3');

valid = [packet_report.applied] & [packet_report.fcs_pass];
fprintf('\n=== QM35 CIR slow-phase analysis ===\n');
fprintf('Packets             : %d\n', packet_count);
fprintf('Reliable correction : %d (%.1f%%)\n', nnz(valid), ...
    100 * mean(valid));
printMetric('Subspace coherence', ...
    [packet_report(valid).subspace_coherence], '');
printMetric('Raw nonlinear RMS', ...
    [packet_report(valid).raw_nonlinear_rms_deg], ' deg');
printMetric('Smooth correction RMS', ...
    [packet_report(valid).correction_rms_deg], ' deg');
printMetric('Estimated noise RMS', ...
    [packet_report(valid).noise_rms_deg], ' deg');
printMetric('Explained fraction', ...
    [packet_report(valid).explained_fraction], '');

repetition_time_us = ((1:preamble_repetitions) - 0.5) * ...
    uwbdecoder.constants().PREAMBLE_PERIOD_S * 1e6;
display_rows = find(valid);
display_rows = display_rows(unique(round(linspace( ...
    1, numel(display_rows), min(200, numel(display_rows))))));
figure('Name', 'QM35 CIR slow phase', 'Color', 'w', ...
    'Position', [80 80 1250 780]);
subplot(2, 1, 1);
plot(repetition_time_us, phase_tracks(display_rows, :)' * 180 / pi, ...
    'Color', [0.75 0.80 0.90]);
hold on;
plot(repetition_time_us, median(phase_tracks(valid, :), ...
    1, 'omitnan') * 180 / pi, 'k-', 'LineWidth', 2);
yline(0, 'k:');
xlabel('Time from packet start (\mus)');
ylabel('Slow correction (deg)');
title(sprintf('%d packet-specific smooth phase tracks', nnz(valid)));
grid on;

subplot(2, 1, 2);
histogram([packet_report(valid).correction_rms_deg], 40);
xlabel('Smooth correction RMS (deg)');
ylabel('Packets');
title('Per-packet correction strength');
grid on;
exportgraphics(gcf, fullfile(output_dir, ...
    'cir_slow_phase_analysis.png'), 'Resolution', 180);

function printMetric(name, values, unit)
fprintf('%-20s: p10 %.3f%s | median %.3f%s | p90 %.3f%s\n', ...
    name, prctile(values, 10), unit, median(values), unit, ...
    prctile(values, 90), unit);
end
