%% Rebuild the DW1000 and QM35 sub-SYNC PLL compensation templates.
% The analysis needs a baseline cancellation without PLL/CIR/SFO so that
% fitting_capture - cancelled_capture recovers the regenerated UWB model.
clear;
close all;
clc;

project_dir = fileparts(mfilename('fullpath'));
cd(project_dir);
addpath(project_dir);

profiles = {
    'DW1000', 'F:\UWB基带数据\dw1000_new_3.dat', ...
        fullfile(project_dir, 'decoded_results', 'dw1000_new_3')
    'QM35', 'F:\UWB基带数据\qm35_new_3.dat', ...
        fullfile(project_dir, 'decoded_results', 'qm35_new_3')
    };

for k = 1:size(profiles, 1)
    profile = profiles{k, 1};
    input_file = profiles{k, 2};
    result_dir = profiles{k, 3};
    scan_file = fullfile(result_dir, 'all_frames_cir.mat');
    if ~isfile(scan_file)
        fprintf('\nRebuilding %s decode results ...\n', profile);
        sic_stage_config = struct( ...
            'input_file', input_file, ...
            'phy_profile', profile, ...
            'result_directory', result_dir, ...
            'pll_phase_compensation_repetitions', 10); %#ok<NASGU>
        run(fullfile(project_dir, 'run_decode_uwb_all.m'));
        clear sic_stage_config;
    else
        fprintf('\nReusing %s decode results: %s\n', profile, scan_file);
    end

    metadata_file = fullfile(result_dir, ...
        'cancelled_optimal_complex_metadata.mat');
    output_file = fullfile(result_dir, ...
        'cancelled_optimal_complex.dat');
    summary_file = fullfile(result_dir, ...
        'cancelled_optimal_complex_summary.csv');
    if ~isfile(metadata_file) || ~isfile(output_file)
        fprintf('\nRebuilding %s baseline cancellation ...\n', profile);
        sic_stage_config = struct( ...
            'input_file', input_file, ...
            'output_base_file', input_file, ...
            'phy_profile', profile, ...
            'result_directory', result_dir, ...
            'output_file', output_file, ...
            'metadata_file', metadata_file, ...
            'summary_file', summary_file, ...
            'cancellation_mode', 'optimal_complex', ...
            'remove_synchronous_tone', false, ...
            'tone_coefficient', [], ...
            'enable_pll_phase_compensation', false, ...
            'pll_phase_apply_repetitions', 10, ...
            'enable_cir_slow_phase_compensation', false, ...
            'enable_full_packet_sfo_correction', false); %#ok<NASGU>
        run(fullfile(project_dir, 'run_cancel_all_uwb_packets.m'));
        clear sic_stage_config;
    else
        fprintf('\nReusing %s baseline cancellation: %s\n', ...
            profile, output_file);
    end
end

fprintf('\nLearning 32-bin/SYNC PLL templates ...\n');
run(fullfile(project_dir, 'analyze_uwb_pll_phase_drift.m'));

expected_templates = {
    fullfile(project_dir, 'decoded_results', ...
        'pll_phase_drift_analysis', 'dw1000_new_3', ...
        'subsync_phase_template.csv')
    fullfile(project_dir, 'decoded_results', ...
        'pll_phase_drift_analysis', 'qm35_new_3', ...
        'subsync_phase_template.csv')
    };
for k = 1:numel(expected_templates)
    if ~isfile(expected_templates{k})
        error('regenerate_uwb_pll_templates:TemplateMissing', ...
            'Expected template was not generated: %s', ...
            expected_templates{k});
    end
    fprintf('Generated: %s\n', expected_templates{k});
end
