%% Visualize the waveform of every UWB packet field on one slide.
% The figure is designed as a 16:9 PowerPoint-ready page:
%   SYNC | SFD | STS | PHR | Payload
% The packet is a deterministic IEEE 802.15.4z BPRF waveform generated by
% the Communications Toolbox functions already used in this workspace.
%
% Outputs (when save_outputs is true):
%   generated_uwb_4a/uwb_packet_fields_waveforms.png
%   generated_uwb_4a/uwb_packet_fields_waveforms.mat

clear;
close all;
clc;

this_dir = fileparts(mfilename('fullpath'));
if isempty(this_dir)
    this_dir = pwd;
end
addpath(this_dir);

%% -------------------- User parameters -------------------------------
sample_rate_hz = 998.4e6;
code_index = 9;
preamble_repetitions = 64;
sfd_number = 2;
sts_packet_configuration = 1;   % Insert STS between SFD and PHR.
payload_data_bytes = uint8(0:10);
peak_amplitude = 0.8;
save_outputs = true;
show_figure = true;

assert(sample_rate_hz == 998.4e6, ...
    'This script expects the workspace HRP sample rate of 998.4 MHz.');
assert(sts_packet_configuration == 1, ...
    'This visualization is intended for a packet containing an STS field.');

%% -------------------- Build a deterministic PSDU ---------------------
% IEEE 802.15.4 stores each byte least-significant bit first on the PHY.
fcs_value = uwbdecoder.ieee802154CRC16(payload_data_bytes);
fcs_bytes = uint8([bitand(fcs_value, uint16(255)); ...
    bitshift(fcs_value, -8)]);
psdu_bytes = [payload_data_bytes(:); fcs_bytes(:)];
psdu_bits = bytesToLsbBits(psdu_bytes);

%% -------------------- Generate BPRF waveform -------------------------
cfg = lrwpanHRPConfig(Mode='BPRF', MeanPRF=62.4, ...
    DataRate=6.81, PHRDataRate=0.85, SamplesPerPulse=2, ...
    STSPacketConfiguration=sts_packet_configuration, ...
    CodeIndex=code_index, PreambleDuration=preamble_repetitions, ...
    SFDNumber=sfd_number, Ranging=false, PSDULength=numel(psdu_bytes));

waveform = lrwpanWaveformGenerator(double(psdu_bits), cfg);
waveform = waveform(:);
waveform = waveform * (peak_amplitude / max(abs(waveform)));

field_indices = lrwpanHRPFieldIndices(cfg);
field_names = {'SYNC', 'SFD', 'STS', 'PHR', 'Payload'};
field_colors = [
    0.28 0.47 0.76;  % SYNC
    0.96 0.42 0.14;  % SFD
    0.38 0.62 0.82;  % STS
    0.44 0.67 0.25;  % PHR
    0.98 0.70 0.10]; % Payload

for field_index = 1:numel(field_names)
    field_name = field_names{field_index};
    field_range = field_indices.(field_name);
    assert(field_range(1) >= 1 && field_range(2) <= numel(waveform) && ...
        field_range(1) <= field_range(2), ...
        'Invalid %s field indices.', field_name);
end

%% -------------------- Build the one-page figure ----------------------
fig = figure('Name', 'UWB packet field waveforms', ...
    'Color', 'w', 'Units', 'pixels', 'Position', [40 40 1920 1080], ...
    'Visible', ternary(show_figure, 'on', 'off'));

annotation(fig, 'textbox', [0.055 0.935 0.89 0.045], ...
    'String', 'UWB Packet Waveforms', 'EdgeColor', 'none', ...
    'FontName', 'Arial', 'FontSize', 28, 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'middle');
annotation(fig, 'textbox', [0.055 0.902 0.89 0.03], ...
    'String', sprintf(['IEEE 802.15.4z BPRF  |  code index %d  |  ', ...
    '%d SYNC symbols  |  %.2f Mb/s  |  %.1f MHz PRF'], ...
    code_index, preamble_repetitions, 6.81, 62.4), ...
    'EdgeColor', 'none', 'FontName', 'Arial', 'FontSize', 13, ...
    'Color', [0.30 0.30 0.30], 'HorizontalAlignment', 'left');

plotPacketStructure(axes('Parent', fig, 'Position', [0.055 0.765 0.89 0.105]), ...
    cfg, field_names, field_colors, sample_rate_hz);

waveform_positions = [
    0.055 0.470 0.275 0.245;
    0.362 0.470 0.275 0.245;
    0.669 0.470 0.275 0.245;
    0.055 0.125 0.428 0.245;
    0.517 0.125 0.428 0.245];

for field_index = 1:numel(field_names)
    field_name = field_names{field_index};
    plotPacketField(axes('Parent', fig, ...
        'Position', waveform_positions(field_index, :)), ...
        waveform, field_indices.(field_name), ...
        field_name, field_colors(field_index, :), sample_rate_hz);
end

annotation(fig, 'textbox', [0.055 0.055 0.89 0.035], ...
    'String', sprintf(['Waveform: normalized in-phase component  |  ', ...
    'Fs = %.1f MHz  |  PSDU = %d bytes  |  FCS = 0x%04X'], ...
    sample_rate_hz / 1e6, numel(psdu_bytes), fcs_value), ...
    'EdgeColor', 'none', 'FontName', 'Arial', 'FontSize', 12, ...
    'Color', [0.35 0.35 0.35], 'HorizontalAlignment', 'left');

%% -------------------- Save reproducible results ----------------------
metadata = struct();
metadata.protocol = 'IEEE 802.15.4z BPRF';
metadata.sample_rate_hz = sample_rate_hz;
metadata.mean_prf_mhz = 62.4;
metadata.data_rate_mbps = 6.81;
metadata.code_index = code_index;
metadata.preamble_repetitions = preamble_repetitions;
metadata.sfd_number = sfd_number;
metadata.sts_packet_configuration = sts_packet_configuration;
metadata.psdu_bytes = psdu_bytes;
metadata.fcs_value = fcs_value;
metadata.field_indices = field_indices;
metadata.field_durations_us = fieldDurationsUs(field_indices, sample_rate_hz);
metadata.waveform_samples = numel(waveform);
metadata.duration_us = numel(waveform) / sample_rate_hz * 1e6;

fprintf('\n=== UWB packet field waveform figure ===\n');
fprintf('Protocol / code        : %s / %d\n', metadata.protocol, code_index);
fprintf('SYNC / SFD / STS       : %d symbols / SFD #%d / config %d\n', ...
    preamble_repetitions, sfd_number, sts_packet_configuration);
fprintf('PSDU / FCS             : %d bytes / 0x%04X\n', ...
    numel(psdu_bytes), fcs_value);
fprintf('Waveform               : %d samples, %.3f us\n', ...
    numel(waveform), metadata.duration_us);

for field_index = 1:numel(field_names)
    field_name = field_names{field_index};
    range = field_indices.(field_name);
    fprintf('%-7s               : samples %d..%d, %.3f us\n', ...
        field_name, range(1), range(2), metadata.field_durations_us.(field_name));
end

if save_outputs
    output_dir = fullfile(this_dir, 'generated_uwb_4a');
    if ~isfolder(output_dir)
        mkdir(output_dir);
    end
    png_file = fullfile(output_dir, 'uwb_packet_fields_waveforms.png');
    mat_file = fullfile(output_dir, 'uwb_packet_fields_waveforms.mat');
    exportgraphics(fig, png_file, 'Resolution', 220);
    save(mat_file, 'waveform', 'cfg', 'field_indices', 'psdu_bytes', ...
        'metadata', '-v7.3');
    fprintf('PNG                    : %s\n', png_file);
    fprintf('MAT                    : %s\n', mat_file);
end

%% -------------------- Local helper functions -------------------------
function bits = bytesToLsbBits(bytes)
bytes = uint8(bytes(:));
bits = false(8 * numel(bytes), 1);
for byte_index = 1:numel(bytes)
    bit_range = (byte_index - 1) * 8 + (1:8);
    bits(bit_range) = logical(bitget(bytes(byte_index), 1:8));
end
end

function plotPacketStructure(ax, cfg, field_names, colors, sample_rate_hz)
hold(ax, 'on');
field_widths = zeros(1, numel(field_names));
for k = 1:numel(field_names)
    field_range = lrwpanHRPFieldIndices(cfg).(field_names{k});
    field_widths(k) = field_range(2) - field_range(1) + 1;
end
field_starts = [0, cumsum(field_widths(1:end-1))];
field_ends = cumsum(field_widths);
total_samples = sum(field_widths);

for k = 1:numel(field_names)
    left = field_starts(k);
    right = field_ends(k);
    patch(ax, [left right right left] / sample_rate_hz * 1e6, ...
        [0 0 1 1], colors(k, :), 'EdgeColor', [1 1 1], 'LineWidth', 1.0);
    center = (left + right) / 2 / sample_rate_hz * 1e6;
    duration_us = field_widths(k) / sample_rate_hz * 1e6;
    label = sprintf('%s\n%.1f \\mus', field_names{k}, duration_us);
    text(ax, center, 0.5, label, 'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
        'FontSize', 14, 'FontWeight', 'bold', 'Color', textColor(colors(k, :)));
end

set(ax, 'YLim', [0 1], 'YTick', [], 'Box', 'on', 'FontName', 'Arial', ...
    'FontSize', 11, 'LineWidth', 0.8, 'XColor', [0.30 0.30 0.30]);
xlabel(ax, 'Packet time (\mus)', 'FontName', 'Arial', 'FontSize', 12);
xlim(ax, [0 total_samples / sample_rate_hz * 1e6]);
title(ax, 'Packet structure and actual field durations', ...
    'FontName', 'Arial', 'FontSize', 14, 'FontWeight', 'bold');
grid(ax, 'on');
end

function plotPacketField(ax, waveform, field_range, field_name, color, sample_rate_hz)
field = real(waveform(field_range(1):field_range(2)));
field = field / max(abs(waveform));
max_plot_points = 4500;
stride = max(1, ceil(numel(field) / max_plot_points));
sample_indices = 1:stride:numel(field);
time_us = (sample_indices - 1) / sample_rate_hz * 1e6;

plot(ax, time_us, field(sample_indices), 'Color', color, 'LineWidth', 0.75);
hold(ax, 'on');
yline(ax, 0, '-', 'Color', [0.55 0.55 0.55], 'LineWidth', 0.55);
grid(ax, 'on');
box(ax, 'on');
xlim(ax, [time_us(1), max(time_us(end), eps)]);
ylim(ax, [-1.05 1.05]);
set(ax, 'FontName', 'Arial', 'FontSize', 10, 'LineWidth', 0.8, ...
    'GridAlpha', 0.22, 'Layer', 'top');
xlabel(ax, 'Relative time (\mus)', 'FontName', 'Arial', 'FontSize', 10);
ylabel(ax, 'Normalized I', 'FontName', 'Arial', 'FontSize', 10);
title(ax, sprintf('%s  |  %d samples', field_name, numel(field)), ...
    'FontName', 'Arial', 'FontSize', 14, 'FontWeight', 'bold', ...
    'Color', color);
end

function durations = fieldDurationsUs(field_indices, sample_rate_hz)
names = fieldnames(field_indices);
durations = struct();
for k = 1:numel(names)
    field_range = field_indices.(names{k});
    durations.(names{k}) = (field_range(2) - field_range(1) + 1) / ...
        sample_rate_hz * 1e6;
end
end

function color = textColor(background)
if mean(background) > 0.62
    color = [0.08 0.08 0.08];
else
    color = [1 1 1];
end
end

function value = ternary(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
