function params = defaultOptions()
%DEFAULTOPTIONS Return the default X410/DW1000 decoder configuration.
%   PARAMS = DEFAULTOPTIONS() returns the scalar structure whose fields
%   configure the decoder: capture path, radio frequencies, HRP PHY
%   parameters, interference-cancellation settings, and plot flags. Pass
%   the result to MERGEOPTIONS to apply user overrides.
%
%   See also MERGEOPTIONS, CONSTANTS.

projectDirectory = fileparts(fileparts(mfilename('fullpath')));
params = struct('file_name', 'F:\UWB基带数据\DW1000_2.dat', ...
    'helper_path', fullfile(projectDirectory, 'helpers'), 'fs_rx', 737.28e6, ...
    'x410_center_frequency', 6500e6, ...
    'dw1000_center_frequency', 6489.6e6, 'ant_num', 1, ...
    'channel_index', 1, 'sample_offset', 0, 'sample_num', 1.5e6, ...
    'enable_interference_cancellation', true, ...
    'interference_quiet_offset', 400000, ...
    'interference_quiet_num', 1500000, 'interference_tone_bin', -169, ...
    'interference_period_samples', 512, ...
    'interference_coefficient', [], ...
    'blank_intervals', [], ...
    'blank_taper_samples', 256, ...
    'blank_weight', 0, ...
    'preamble_repetitions', 256, ...
    'cir_repetitions', 64, ...
    'cir_skip_initial_repetitions', [], ...
    'cir_pre_samples', 8, ...
    'cir_post_samples', 30, ...
    'cir_max_path_m', [], ...
    'max_psdu_bytes', 127, ...
    'enable_frame_crop', true, ...
    'verbose', false, ...
    'code_index', 10, 'data_rate', 6.81, ...
    'sfd_mode', 'decawave', ...
    'decawave_sfd', [-1; -1; -1; -1; 1; -1; 0; 0], ...
    'ieee_sfd', [0; 1; 0; -1; 1; 0; 0; -1], ...
    'sfd4z_1', [-1; -1; 1; -1], ...
    'sfd4z_2', [-1; -1; -1; 1; -1; -1; 1; -1], ...
    'sfd4z_3', [-1; -1; -1; -1; -1; 1; 1; -1; ...
        -1; 1; -1; 1; -1; -1; 1; -1], ...
    'sfd4z_4', [-1; -1; -1; -1; -1; -1; -1; 1; ...
        -1; -1; 1; -1; -1; 1; -1; 1; -1; 1; -1; -1; ...
        -1; 1; 1; -1; -1; -1; 1; -1; 1; 1; -1; -1], ...
    'show_plots', true);
end
