function result = packageResult(params, reference, interference, ...
        preamble, sfdSymbols, cir, chips, sfd, frame)
%PACKAGERESULT Convert internal stage structures to the public result API.
%   RESULT = PACKAGERESULT(PARAMS, REFERENCE, INTERFERENCE, PREAMBLE,
%   SFDSYMBOLS, CIR, CHIPS, SFD, FRAME) flattens every decoder stage
%   output into the single structure returned to callers of
%   decode_uwb.
%
%   See also DECODE_X410_DW1000.

result = struct('settings', params, 'phy_config', reference.cfg, ...
    'interference', interference);
result.preamble = struct('metric_peak', preamble.metric_peak, ...
    'detector', preamble.detector, ...
    'detection_threshold', preamble.threshold, 'peak_indices', preamble.peaks, ...
    'detected_repetitions', preamble.detected_repetitions, ...
    'samples_per_repetition', preamble.measured_period, ...
    'sample_clock_error_ppm', preamble.clock_error_ppm, ...
    'start_sample', preamble.start_sample, ...
    'carrier_frequency_offset_hz', preamble.frequency_offset_hz, ...
    'sfd_waveform_correlation', preamble.sfd_waveform_correlation);
result.cir = cir;
result.sfd_symbol_diagnostics = sfdSymbols;
result.sfd = sfd;
result.phr = struct('start_chip', frame.phr_start, 'end_chip', frame.phr_end, ...
    'coded_bits', frame.coded_phr, 'secded_pass', frame.secded_pass, ...
    'psdu_length_bytes', frame.psdu_length);
result.payload = struct('start_chip', frame.payload_start, ...
    'end_chip', frame.payload_end, 'bits', frame.bits, 'bytes', frame.bytes, ...
    'fcs_received', frame.received_fcs, 'fcs_calculated', frame.calculated_fcs, ...
    'fcs_pass', frame.fcs_pass);
result.soft_chips = chips.soft;
end
