function reference = buildDw1000Reference(params)
%BUILDDW1000REFERENCE Build waveform and sparse spreading-code references.
cfg = lrwpanHRPConfig(Mode='802.15.4a', MeanPRF=62.4, ...
    DataRate=params.data_rate, PreambleDuration=64, ...
    CodeIndex=params.code_index, SamplesPerPulse=2, PSDULength=1);
tx = lrwpanWaveformGenerator(zeros(8, 1), cfg);
indices = lrwpanHRPFieldIndices(cfg);
samples_per_symbol = indices.SYNC(end)/cfg.PreambleDuration;
preamble_waveform = tx(1:samples_per_symbol);
preamble_waveform = preamble_waveform(:)/(norm(preamble_waveform)+eps);
code = lrwpan.internal.HRPCodes(params.code_index);
spread_code = zeros(length(code)*cfg.PreambleSpreadingFactor, 1);
spread_code(1:cfg.PreambleSpreadingFactor:end) = code(:);
sampled_code = zeros(length(spread_code)*cfg.SamplesPerPulse, 1);
sampled_code(1:cfg.SamplesPerPulse:end) = spread_code;
reference = struct('cfg', cfg, 'fs', cfg.SampleRate, ...
    'samples_per_symbol', samples_per_symbol, ...
    'preamble_waveform', preamble_waveform, ...
    'spread_code', spread_code, 'sampled_code', sampled_code, ...
    'chips_per_symbol', length(spread_code), ...
    'code_energy', real(sampled_code'*sampled_code));
end
